### ISSUE TITLE
Using any caching method that isn't 'db' seems to break pages

### ISSUE THREAD

**Issue by smt923** [OUGC-Network/OUGC-Pages#8]
If I use memcached or APC the pages simply return "The selected page seems to be invalid", setting caching back to 'db' in inc/config.php will instantly fix the issue with pages, categorys still load fine

**Comment by Sama34** [comment]
I'm not sure why would this occur but I will check it.

**Comment by smt923** [comment]
In the cache manager? rebuild and reload all didn't fix it, still the same issue, page it's self is invalid but categorys work fine, no php/html server errors or anything like that either

**Comment by Sama34** [comment]
With the current pre-release package _Page Content_ is no longer cached but instead is queried when necessary.

Additionally an option to use a classic theme template is added, thus you could left the _Page Content_ as empty and instead use a template for it (probably global to avoid a per-theme template being required).

I think any of the two changes should make your issue moot in the upcoming release.
